
// src/sw.js
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

self.addEventListener('push', function (event) {
    if (event.data) {
        const payload = event.data.json();
        const title = payload.title || 'New Notification';
        const options = {
            body: payload.body,
            icon: '/pwa-192x192.png', // Replace with your app icon
            badge: '/pwa-192x192.png',
            data: payload.data
        };

        event.waitUntil(
            self.registration.showNotification(title, options)
        );
    }
});

self.addEventListener('notificationclick', function (event) {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function (clientList) {
            // Check if app is open
            if (clientList.length > 0) {
                let client = clientList[0];
                for (let i = 0; i < clientList.length; i++) {
                    if (clientList[i].focused) {
                        client = clientList[i];
                    }
                }
                if (client) {
                    client.focus();
                    if (event.notification.data && event.notification.data.url) {
                        client.navigate(event.notification.data.url);
                    }
                    return;
                }
            }
            if (clients.openWindow) {
                const url = (event.notification.data && event.notification.data.url) ? event.notification.data.url : '/';
                return clients.openWindow(url);
            }
        })
    );
});
